#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

echo "Quick check summary for BaseDR_Docker"

echo "1) run.sh test (endpoints smoke)"
./run.sh test || { echo "run.sh test failed"; exit 2; }

echo
echo "2) Prometheus targets"
curl -sS http://localhost:9090/api/v1/targets || echo "Prometheus unreachable"

echo
echo "3) Verify important metrics counts (db_fetch_duration_ms_count, api_rest_latency_ms_count, api_graphql_latency_ms_count)"
for q in "db_fetch_duration_ms_count" "api_rest_latency_ms_count" "api_graphql_latency_ms_count"; do
  echo "Query: $q"
  curl -sS "http://localhost:9090/api/v1/query?query=$q" || echo "query failed"
  echo
done

echo
echo "4) Grafana registered dashboards (search)"
curl -sS http://admin:admin@localhost:3000/api/search || echo "Grafana unreachable"

echo
echo "5) Check recent aggregate file (if exists)"
if [ -f services/research-api/logs/metrics_summary.json ]; then
  echo "metrics_summary.json (tail):"
  tail -n 80 services/research-api/logs/metrics_summary.json
else
  echo "metrics_summary.json not found"
fi

echo
echo "6) Where to find stored evidence and logs"
cat <<'EOT'
- Prometheus TSDB (time-series history) is persisted in docker volume 'prometheus_data' mounted to /prometheus in the container.
- Grafana stores dashboards and its sqlite DB in docker volume 'grafana_data' mounted to /var/lib/grafana; dashboards JSON are in ./monitoring/dashboards.
- Aggregated summaries: services/research-api/logs/metrics_summary.json (generated by ./run.sh aggregate)
- Artillery results (if run) are in ./logs/artillery_*.json inside the project.
- Seed and benchmark scripts log to services/research-api/logs/ and tools container logs.
EOT

echo
echo "Quick-check complete"
