{
 "title": "Queries - GraphQL",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_sum{api_type=\"graphql\"}[1m]) \r\n/ \r\nrate(http_request_duration_ms_count{api_type=\"graphql\"}[1m])",
     "legendFormat": "Promedio"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http_request_duration_ms_bucket{api_type=\"graphql\"}[1m]))",
     "legendFormat": "Mediana"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_ms_bucket{api_type=\"graphql\"}[1m]))",
     "legendFormat": "Percentil 95"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(http_requests_total{api_type=\"graphql\"}[1m])",
     "legendFormat": "Peticiones por segundo"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(errors_total{api_type=\"graphql\"}[1m])",
     "legendFormat": "Errores por segundo"
    }
   ]
  },
  {
   "title": "Payload Size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(response_size_bytes_sum{api_type=\"graphql\"}[1m])",
     "legendFormat": "Bytes por segundo"
    }
   ]
  },
  {
   "title": "Time To First Byte (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(ttfb_ms_bucket{api_type=\"graphql\"}[1m]))",
     "legendFormat": "Percentil 95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(ttfb_ms_bucket{api_type=\"graphql\"}[1m]))",
     "legendFormat": "Mediana"
    }
   ]
  },
  {
   "title": "CPU Usage (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "cpu_usage_percent{api_type=\"graphql\"}",
     "legendFormat": "Porcentaje"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "memory_usage_bytes{api_type=\"graphql\"}",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Latency p99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_ms_bucket{api_type=\"graphql\"}[1m]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "% Time in DB (graphql)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(db_fetch_duration_ms_sum{api_type=\"graphql\"}[5m])) / sum(rate(http_request_duration_ms_sum{api_type=\"graphql\"}[5m]))",
     "legendFormat": "% DB time"
    }
   ]
  }
 ]
}