{
 "title": "Metricas GraphQL",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_sum[1m]) \r\n/ \r\nrate(http_request_duration_ms_count[1m])",
     "legendFormat": "Promedio"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http_request_duration_ms_bucket[1m]))",
     "legendFormat": "Mediana"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_ms_bucket[1m]))",
     "legendFormat": "Percentil 95"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "Peticiones por segundo" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "rate(errors_total[1m])", "legendFormat": "Errores por segundo" }
   ]
  },
  {
   "title": "Payload Size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(response_size_bytes_sum[1m])",
     "legendFormat": "Bytes por segundo"
    }
   ]
  },
  {
   "title": "Time To First Byte (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(ttfb_ms_bucket[1m]))",
     "legendFormat": "Percentil 95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(ttfb_ms_bucket[1m]))",
     "legendFormat": "Mediana"
    }
   ]
  },
  {
   "title": "CPU Usage (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "Porcentaje" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "memory_usage_bytes", "legendFormat": "Bytes" }
   ]
  }
 ]
}